GET http://127.0.0.1:8080
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoeXVuZ2V1bmpvQHdldmVyc2Vjb21wYW55LmNvbSIsInJvbGUiOiJNQU5BR0VSIiwiaWF0IjoxNjU2MzkyNzEyLCJleHAiOjE2NTYzOTMzMTJ9.ZjRdIphneya3OhfSCf7t6yd0_vPmoK0t9DH7c1hfTgI